export const goalData = [
  /* ===== 초급 ===== */
  {
    id: 1,
    title: "5KM",
    subtitle: "처음 시작하는 단계",
    description: "러닝에 익숙해지는 첫 걸음",
    level: "초급",
    status: "진행중",
    goalType: "distance",
    targetDistance: 5,
  },
  {
    id: 2,
    title: "10KM",
    subtitle: "러닝의 기본을 다지는 단계 ",
    description: "편안한 속도로 꾸준히 완주하는 것이 목표 ",
    level: "초급",
    status: "완료",
    goalType: "distance",
    targetDistance: 10,
  },
  {
    id: 3,
    title: "21KM",
    subtitle: "하프 마라톤 도전 ",
    description: "10KM 에 익숙해지면 도전하는 중급 러너의 첫 관문",
    level: "초급",
    status: "미완료",
    goalType: "distance",
    targetDistance: 21,
  },
  {
    id: 4,
    title: "42KM",
    subtitle: "풀 마라톤 완주",
    description: "모든 러너의 꿈! 충분한 준비 후 도전하는 최종 목표",
    level: "초급",
    goalType: "distance",
    targetDistance: 42,
  },

  /* ===== 중급 ===== */
  {
    id: 5,
    title: "5km 페이스 챌린지",
    subtitle: "빠른 페이스 스피드 챌린지",
    description: "목표 페이스: 5'00\" /km",
    level: "중급",
    goalType: "pace",
    targetPace: "5:00",
  },
  {
    id: 6,
    title: "거리 챌린지 - 5km",
    subtitle: "3km ~ 하프까지 누적 거리 챌린지",
    description: "목표 페이스: 5'00\" /km",
    level: "중급",
    goalType: "distance",
    targetDistance: 5,
  },
  {
    id: 7,
    title: "고급 레벨 챌린지",
    subtitle: "레벨 업을 위한 챌린지",
    description: "목표 페이스: 4'30\" /km",
    level: "중급",
    goalType: "pace",
    targetPace: "4:30",
  },
  {
    id: 8,
    title: "5km 페이스 챌린지 - Step 1",
    subtitle: "빠른 페이스 스피드 챌린지",
    description: "목표 페이스: 5'00\" /km",
    level: "중급",
    goalType: "pace",
    targetPace: "5:00",
  },
  {
    id: 9,
    title: "5km 페이스 챌린지 - Step 2",
    subtitle: "빠른 페이스 스피드 챌린지",
    description: "목표 페이스: 4'55\" /km",
    level: "중급",
    goalType: "pace",
    targetPace: "4:55",
    prerequisiteId: 8,
  },
  {
    id: 10,
    title: "거리 챌린지 - 5km",
    subtitle: "3km ~ 하프까지 누적 거리 챌린지",
    description: "목표 페이스: 5'00\" /km",
    level: "중급",
    goalType: "distance",
    targetDistance: 5,
  },
  {
    id: 11,
    title: "거리 챌린지 - 10km",
    subtitle: "3km ~ 하프까지 누적 거리 챌린지",
    description: "목표 페이스: 5'00\" /km",
    level: "중급",
    goalType: "distance",
    targetDistance: 10,
  },
  {
    id: 12,
    title: "고급 레벨 챌린지",
    subtitle: "레벨 업을 위한 챌린지",
    description: "목표 페이스: 4'30\" /km",
    level: "중급",
    goalType: "pace",
    targetPace: "4:30",
  },

  /* ===== 고급 ===== */
  {
    id: 13,
    title: "5km 페이스 챌린지",
    subtitle: "빠른 페이스 스피드 챌린지",
    description: "목표 페이스: 4'30\" /km",
    level: "고급",
    goalType: "pace",
    targetPace: "4:30",
  },
  {
    id: 14,
    title: "5km 페이스 챌린지",
    subtitle: "빠른 페이스 스피드 챌린지",
    description: "목표 페이스: 4'20\" /km",
    level: "고급",
    goalType: "pace",
    targetPace: "4:20",
  },
  {
    id: 15,
    title: "5km 페이스 챌린지",
    subtitle: "빠른 페이스 스피드 챌린지",
    description: "목표 페이스: 4'10\" /km",
    level: "고급",
    goalType: "pace",
    targetPace: "4:10",
  },
  {
    id: 16,
    title: "5km 페이스 챌린지",
    subtitle: "빠른 페이스 스피드 챌린지",
    description: "목표 페이스: 4'00\" /km",
    level: "고급",
    goalType: "pace",
    targetPace: "4:00",
  },
  {
    id: 17,
    title: "5km 페이스 챌린지 - Step 1",
    subtitle: "단계별 스피드 챌린지",
    description: "목표 페이스: 4'20\" /km",
    level: "고급",
    goalType: "pace",
    targetPace: "4:20",
  },
  {
    id: 18,
    title: "5km 페이스 챌린지 - Step 2",
    subtitle: "단계별 스피드 챌린지",
    description: "목표 페이스: 4'10\" /km",
    level: "고급",
    goalType: "pace",
    targetPace: "4:10",
    prerequisiteId: 17,
  },
  {
    id: 19,
    title: "거리 챌린지 - 5km",
    subtitle: "고급 레벨 거리 챌린지",
    description: "목표 페이스: 4'30\" /km",
    level: "고급",
    goalType: "distance",
    targetDistance: 5,
  },
  {
    id: 20,
    title: "거리 챌린지 - 10km",
    subtitle: "고급 레벨 거리 챌린지",
    description: "목표 페이스: 4'30\" /km",
    level: "고급",
    goalType: "distance",
    targetDistance: 10,
  },
];
